window.DIMM_DOMESTIC_MODULE_COSTS = {
  "sourceFile": "/Users/chenliqiang/Documents/成本核算/国内模组加工成本2026.5.20.xlsx",
  "coverage": {
    "sourceFile": "/Users/chenliqiang/Documents/成本核算/国内模组加工成本2026.5.20.xlsx",
    "exchangeRate": 6.865,
    "recordCount": 38,
    "mappedRows": 13,
    "unmappedRows": 25,
    "factories": [
      "晟中",
      "自采物料"
    ],
    "moduleForms": [
      "DDR4 SODIMM",
      "DDR4 UDIMM",
      "DDR5 SODIMM",
      "DDR5 UDIMM"
    ]
  },
  "records": [
    {
      "sourceRow": 3,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 UDIMM",
      "generation": "DDR4",
      "moduleType": "UDIMM",
      "capacity": "4GB",
      "rank": "1Rx8",
      "boardCode": "B84URCA2",
      "pcb": "欣强1Rx8 (贴8颗）B84URCA2 2.10",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 9.9,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 12.5,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.1,
      "testNoRowHammerRmb": 2.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 18.03,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 18.53,
      "rowHammerTestRmb": 2.5,
      "rowHammerTotalRmb": 18.53,
      "remark": "",
      "formulas": {
        "pcbaBom": "=10.9+1.6",
        "standardTotal": "=SUM(M3:R3)",
        "customTotal": "=SUM(S3:U3)",
        "rowHammerTotal": "=S3-P3+W3"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 5.53,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 4,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 UDIMM",
      "generation": "DDR4",
      "moduleType": "UDIMM",
      "capacity": "8GB",
      "rank": "1Rx8",
      "boardCode": "B84URCA2",
      "pcb": "欣强1Rx8 (贴8颗）B84URCA2 2.10",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 9.9,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 12.5,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.1,
      "testNoRowHammerRmb": 2.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 18.03,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 18.53,
      "rowHammerTestRmb": 2.5,
      "rowHammerTotalRmb": 18.53,
      "remark": "",
      "formulas": {
        "pcbaBom": "=10.9+1.6",
        "standardTotal": "=SUM(M4:R4)",
        "customTotal": "=SUM(S4:U4)",
        "rowHammerTotal": "=S4-P4+W4"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 5.53,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 5,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 UDIMM",
      "generation": "DDR4",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "2Rx8",
      "boardCode": "B84URCB2",
      "pcb": "欣强2Rx8 (贴16颗）B84URCB2 0.70",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 10.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 14.4,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.3,
      "testNoRowHammerRmb": 2.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 21.83,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 22.43,
      "rowHammerTestRmb": 3.2,
      "rowHammerTotalRmb": 22.53,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M5:R5)",
        "customTotal": "=SUM(S5:U5)",
        "rowHammerTotal": "=S5-P5+W5"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 0.7
    },
    {
      "sourceRow": 6,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 UDIMM",
      "generation": "DDR4",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "B84URCA2",
      "pcb": "欣强1Rx8 (贴8颗）B84URCA2 2.10",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 9.9,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 12.5,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.1,
      "testNoRowHammerRmb": 2.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 18.53,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 19.03,
      "rowHammerTestRmb": 3.2,
      "rowHammerTotalRmb": 19.23,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M6:R6)",
        "customTotal": "=SUM(S6:U6)",
        "rowHammerTotal": "=S6-P6+W6"
      },
      "matchedPartNumbers": [
        "PBA0018C2008"
      ],
      "mappedPartNumber": "PBA0018C2008",
      "processingCostRmb": 6.03,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.7
    },
    {
      "sourceRow": 7,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 UDIMM",
      "generation": "DDR4",
      "moduleType": "UDIMM",
      "capacity": "32GB",
      "rank": "2Rx8",
      "boardCode": "B84URCB2",
      "pcb": "欣强2Rx8 (贴16颗）B84URCB2 0.70",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 10.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 16.4,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.3,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 24.83,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 25.43,
      "rowHammerTestRmb": 4.8,
      "rowHammerTotalRmb": 26.13,
      "remark": "",
      "formulas": {
        "pcbaBom": "=14.2+2.2",
        "standardTotal": "=SUM(M7:R7)",
        "customTotal": "=SUM(S7:U7)",
        "rowHammerTotal": "=S7-P7+W7"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 1.3
    },
    {
      "sourceRow": 8,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 SODIMM",
      "generation": "DDR4",
      "moduleType": "SODIMM",
      "capacity": "4GB",
      "rank": "1Rx8",
      "boardCode": "B84SRCA1",
      "pcb": "欣强1Rx8 (贴8颗）B84SRCA1 2.0",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 8.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 11.9,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.1,
      "testNoRowHammerRmb": 2.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 17.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 17.93,
      "rowHammerTestRmb": 2.5,
      "rowHammerTotalRmb": 17.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M8:R8)",
        "customTotal": "=SUM(S8:U8)",
        "rowHammerTotal": "=S8-P8+W8"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 5.53,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 9,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 SODIMM",
      "generation": "DDR4",
      "moduleType": "SODIMM",
      "capacity": "8GB",
      "rank": "1Rx8",
      "boardCode": "B84SRCA2",
      "pcb": "欣强1Rx8 (贴8颗）B84SRCA2 3.0",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 8.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 11.9,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.1,
      "testNoRowHammerRmb": 2.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 17.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 17.93,
      "rowHammerTestRmb": 2.5,
      "rowHammerTotalRmb": 17.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M9:R9)",
        "customTotal": "=SUM(S9:U9)",
        "rowHammerTotal": "=S9-P9+W9"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 5.53,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 10,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 SODIMM",
      "generation": "DDR4",
      "moduleType": "SODIMM",
      "capacity": "16GB",
      "rank": "2Rx8",
      "boardCode": "BA4S8F4",
      "pcb": "欣强2Rx8 (贴16颗）BA4S8F4 1.00",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 9.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 13.4,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.3,
      "testNoRowHammerRmb": 2.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 20.83,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 21.43,
      "rowHammerTestRmb": 3.2,
      "rowHammerTotalRmb": 21.53,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M10:R10)",
        "customTotal": "=SUM(S10:U10)",
        "rowHammerTotal": "=S10-P10+W10"
      },
      "matchedPartNumbers": [
        "PBA0018C2011"
      ],
      "mappedPartNumber": "PBA0018C2011",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 0.7
    },
    {
      "sourceRow": 11,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 SODIMM",
      "generation": "DDR4",
      "moduleType": "SODIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "B84SRCA2",
      "pcb": "欣强1Rx8 (贴8颗）B84SRCA2 3.0",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 8.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 11.9,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.1,
      "testNoRowHammerRmb": 2.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 17.93,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 18.43,
      "rowHammerTestRmb": 3.2,
      "rowHammerTotalRmb": 18.63,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M11:R11)",
        "customTotal": "=SUM(S11:U11)",
        "rowHammerTotal": "=S11-P11+W11"
      },
      "matchedPartNumbers": [
        "PBA0018C2010"
      ],
      "mappedPartNumber": "PBA0018C2010",
      "processingCostRmb": 6.03,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.7
    },
    {
      "sourceRow": 12,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR4 SODIMM",
      "generation": "DDR4",
      "moduleType": "SODIMM",
      "capacity": "32GB",
      "rank": "2Rx8",
      "boardCode": "BA4S8F4",
      "pcb": "欣强2Rx8 (贴16颗 BA4S8F4 1.00",
      "spdHub": "贝岭",
      "pmic": "/",
      "inductor": "/",
      "pcbCostRmb": 9.8,
      "pmicCostRmb": 0,
      "spdCostRmb": 0,
      "inductorCostRmb": 0,
      "rcCostRmb": 0,
      "pcbaBomRmb": 15.4,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.3,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 23.83,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 24.43,
      "rowHammerTestRmb": 4.8,
      "rowHammerTotalRmb": 25.13,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M12:R12)",
        "customTotal": "=SUM(S12:U12)",
        "rowHammerTotal": "=S12-P12+W12"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 1.3
    },
    {
      "sourceRow": 13,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "8GB",
      "rank": "1Rx16",
      "boardCode": "B85URCC",
      "pcb": "欣强1Rx16 (贴4颗）B85URCC 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 10.13,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.5,
      "pcbaBomRmb": 19.52,
      "coverCostRmb": 0.6,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 25.85,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 26.35,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H13:L13)",
        "standardTotal": "=SUM(M13:R13)",
        "customTotal": "=SUM(S13:U13)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [
        "PBA0018C2004"
      ],
      "mappedPartNumber": "PBA0018C2004",
      "processingCostRmb": 6.33,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 14,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "8GB",
      "rank": "1Rx16",
      "boardCode": "B85URCC",
      "pcb": "欣强1Rx16 (贴4颗）B85URCC 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.3,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 0.6,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 34.33,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 34.83,
      "rowHammerTestRmb": 4.0,
      "rowHammerTotalRmb": 35.33,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M14:R14)",
        "customTotal": "=SUM(S14:U14)",
        "rowHammerTotal": "=S14-P14+W14"
      },
      "matchedPartNumbers": [
        "PBA0018C2004"
      ],
      "mappedPartNumber": "PBA0018C2004",
      "processingCostRmb": 6.33,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 1.0
    },
    {
      "sourceRow": 15,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "B85URCA",
      "pcb": "欣强1Rx8 (贴8颗）B85URCA 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 9.56,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.39,
      "pcbaBomRmb": 18.84,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 26.27,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 26.77,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H15:L15)",
        "standardTotal": "=SUM(M15:R15)",
        "customTotal": "=SUM(S15:U15)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [
        "PBA0018C2003"
      ],
      "mappedPartNumber": "PBA0018C2003",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 16,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "B85URCA",
      "pcb": "欣强1Rx8 (贴8颗）B85URCA 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.3,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 35.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 35.93,
      "rowHammerTestRmb": 4.0,
      "rowHammerTotalRmb": 35.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M16:R16)",
        "customTotal": "=SUM(S16:U16)",
        "rowHammerTotal": "=S16-P16+W16"
      },
      "matchedPartNumbers": [
        "PBA0018C2003"
      ],
      "mappedPartNumber": "PBA0018C2003",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 17,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "BA5UH11",
      "pcb": "欣强1Rx8 (贴8颗）BA5UH11",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 10.99,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.57,
      "pcbaBomRmb": 20.45,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 28.88,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 29.38,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H17:L17)",
        "standardTotal": "=SUM(M17:R17)",
        "customTotal": "=SUM(S17:U17)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [
        "PBA0018C2012"
      ],
      "mappedPartNumber": "PBA0018C2012",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 18,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "BA5UH11",
      "pcb": "欣强1Rx8 (贴8颗）BA5UH11",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 12.8,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 30.3,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 38.73,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 39.23,
      "rowHammerTestRmb": 6.0,
      "rowHammerTotalRmb": 40.23,
      "remark": "",
      "formulas": {
        "pcbaBom": "=30.3",
        "standardTotal": "=SUM(M18:R18)",
        "customTotal": "=SUM(S18:U18)",
        "rowHammerTotal": "=S18-P18+W18"
      },
      "matchedPartNumbers": [
        "PBA0018C2012"
      ],
      "mappedPartNumber": "PBA0018C2012",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 1.5
    },
    {
      "sourceRow": 19,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "BA5UR02",
      "pcb": "RGB 欣强1Rx8 (贴8颗）BA5UR02",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 15.5,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 46.5,
      "coverCostRmb": 1.2,
      "smtCostRmb": 3.0,
      "testNoRowHammerRmb": 6.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 56.93,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 57.53,
      "rowHammerTestRmb": 7.5,
      "rowHammerTotalRmb": 58.43,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M19:R19)",
        "customTotal": "=SUM(S19:U19)",
        "rowHammerTotal": "=S19-P19+W19"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 10.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 1.5
    },
    {
      "sourceRow": 20,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "24GB",
      "rank": "1Rx8",
      "boardCode": "B85URCA",
      "pcb": "欣强1Rx8 (贴8颗）B85URCA 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 9.56,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.39,
      "pcbaBomRmb": 18.84,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 26.27,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 26.77,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H20:L20)",
        "standardTotal": "=SUM(M20:R20)",
        "customTotal": "=SUM(S20:U20)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 21,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "24GB",
      "rank": "1Rx8",
      "boardCode": "B85URCA",
      "pcb": "欣强1Rx8 (贴8颗）B85URCA 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.3,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 35.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 35.93,
      "rowHammerTestRmb": 4.0,
      "rowHammerTotalRmb": 35.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M21:R21)",
        "customTotal": "=SUM(S21:U21)",
        "rowHammerTotal": "=S21-P21+W21"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 22,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "32GB",
      "rank": "1Rx8",
      "boardCode": "B85URCA",
      "pcb": "欣强1Rx8 (贴8颗）B85URCA 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 9.56,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.39,
      "pcbaBomRmb": 18.84,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 27.27,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 27.77,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H22:L22)",
        "standardTotal": "=SUM(M22:R22)",
        "customTotal": "=SUM(S22:U22)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 23,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "32GB",
      "rank": "1Rx8",
      "boardCode": "B85URCA",
      "pcb": "欣强1Rx8 (贴8颗）B85URCA 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.3,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 36.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 36.93,
      "rowHammerTestRmb": 6.0,
      "rowHammerTotalRmb": 37.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M23:R23)",
        "customTotal": "=SUM(S23:U23)",
        "rowHammerTotal": "=S23-P23+W23"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 1.5
    },
    {
      "sourceRow": 24,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "32GB",
      "rank": "2Rx8",
      "boardCode": "B85URCB",
      "pcb": "欣强2Rx8 (贴16颗）B85URCB 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 11.4,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 36.73,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 37.33,
      "rowHammerTestRmb": 6.0,
      "rowHammerTotalRmb": 38.23,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M24:R24)",
        "customTotal": "=SUM(S24:U24)",
        "rowHammerTotal": "=S24-P24+W24"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.73,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 1.5
    },
    {
      "sourceRow": 25,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "48GB",
      "rank": "2Rx8",
      "boardCode": "B85URCB",
      "pcb": "欣强2Rx8 (贴16颗）B85URCB 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 11.4,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 7.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 40.43,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 41.03,
      "rowHammerTestRmb": 9.0,
      "rowHammerTotalRmb": 42.43,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M25:R25)",
        "customTotal": "=SUM(S25:U25)",
        "rowHammerTotal": "=S25-P25+W25"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 12.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 2.0
    },
    {
      "sourceRow": 26,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "64GB",
      "rank": "2Rx8",
      "boardCode": "B85URCB",
      "pcb": "欣强2Rx8 (贴16颗）B85URCB 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 11.4,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 9.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 42.43,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 43.03,
      "rowHammerTestRmb": 11.0,
      "rowHammerTotalRmb": 44.43,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M26:R26)",
        "customTotal": "=SUM(S26:U26)",
        "rowHammerTotal": "=S26-P26+W26"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 14.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 2.0
    },
    {
      "sourceRow": 27,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 UDIMM",
      "generation": "DDR5",
      "moduleType": "UDIMM",
      "capacity": "64GB",
      "rank": "2Rx8",
      "boardCode": "BA5UH12",
      "pcb": "欣强2Rx8 (贴16颗）BA5UH12",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 15.5,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 33.0,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 9.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 47.43,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 48.03,
      "rowHammerTestRmb": 11.0,
      "rowHammerTotalRmb": 49.43,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M27:R27)",
        "customTotal": "=SUM(S27:U27)",
        "rowHammerTotal": "=S27-P27+W27"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 14.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 2.0
    },
    {
      "sourceRow": 28,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "8GB",
      "rank": "1Rx16",
      "boardCode": "B85SRCC",
      "pcb": "欣强1Rx16(贴4颗）B85SRCC 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 7.84,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.44,
      "pcbaBomRmb": 17.17,
      "coverCostRmb": 0.6,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 23.5,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 24.0,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H28:L28)",
        "standardTotal": "=SUM(M28:R28)",
        "customTotal": "=SUM(S28:U28)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [
        "PBA0018C2006"
      ],
      "mappedPartNumber": "PBA0018C2006",
      "processingCostRmb": 6.33,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 29,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "8GB",
      "rank": "1Rx16",
      "boardCode": "B85SRCC",
      "pcb": "欣强1Rx16(贴4颗）B85SRCC 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 9.9,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 0.6,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 34.33,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 34.83,
      "rowHammerTestRmb": 4.0,
      "rowHammerTotalRmb": 35.33,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M29:R29)",
        "customTotal": "=SUM(S29:U29)",
        "rowHammerTotal": "=S29-P29+W29"
      },
      "matchedPartNumbers": [
        "PBA0018C2006"
      ],
      "mappedPartNumber": "PBA0018C2006",
      "processingCostRmb": 6.33,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 1.0
    },
    {
      "sourceRow": 30,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "16GB",
      "rank": "",
      "boardCode": "自研PCB",
      "pcb": "自研PCB",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 7.22,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.03,
      "pcbaBomRmb": 16.14,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 23.57,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 24.07,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H30:L30)",
        "standardTotal": "=SUM(M30:R30)",
        "customTotal": "=SUM(S30:U30)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 31,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "BA5SRCA",
      "pcb": "欣强1Rx8 (贴8颗）BA5SRCA 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 8.99,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.38,
      "pcbaBomRmb": 18.26,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 25.69,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 26.19,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H31:L31)",
        "standardTotal": "=SUM(M31:R31)",
        "customTotal": "=SUM(S31:U31)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [
        "PBA0018C2005"
      ],
      "mappedPartNumber": "PBA0018C2005",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 32,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "16GB",
      "rank": "1Rx8",
      "boardCode": "BA5SRCA",
      "pcb": "欣强1Rx8 (贴8颗）BA5SRCA 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 9.8,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 35.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 35.93,
      "rowHammerTestRmb": 4.0,
      "rowHammerTotalRmb": 35.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M32:R32)",
        "customTotal": "=SUM(S32:U32)",
        "rowHammerTotal": "=S32-P32+W32"
      },
      "matchedPartNumbers": [
        "PBA0018C2005"
      ],
      "mappedPartNumber": "PBA0018C2005",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 33,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "24GB",
      "rank": "1Rx8",
      "boardCode": "BA5SRCA",
      "pcb": "欣强1Rx8 (贴8颗）BA5SRCA 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 8.99,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.38,
      "pcbaBomRmb": 18.26,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 25.69,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 26.19,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H33:L33)",
        "standardTotal": "=SUM(M33:R33)",
        "customTotal": "=SUM(S33:U33)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 34,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "24GB",
      "rank": "1Rx8",
      "boardCode": "BA5SRCA",
      "pcb": "欣强1Rx8 (贴8颗）BA5SRCA 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 9.8,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 3.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 35.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 35.93,
      "rowHammerTestRmb": 4.0,
      "rowHammerTotalRmb": 35.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M34:R34)",
        "customTotal": "=SUM(S34:U34)",
        "rowHammerTotal": "=S34-P34+W34"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 7.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0.5
    },
    {
      "sourceRow": 35,
      "factory": "自采物料",
      "sourceFactory": "自采物料",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "32GB",
      "rank": "1Rx8",
      "boardCode": "BA5SRCA",
      "pcb": "欣强1Rx8 (贴8颗）BA5SRCA 1.00",
      "spdHub": "GD",
      "pmic": "GD",
      "inductor": "新聿",
      "pcbCostRmb": 8.99,
      "pmicCostRmb": 3.45,
      "spdCostRmb": 3.11,
      "inductorCostRmb": 1.33,
      "rcCostRmb": 1.38,
      "pcbaBomRmb": 18.26,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 26.69,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 27.19,
      "rowHammerTestRmb": 0,
      "rowHammerTotalRmb": 0,
      "remark": "",
      "formulas": {
        "pcbaBom": "=SUM(H35:L35)",
        "standardTotal": "=SUM(M35:R35)",
        "customTotal": "=SUM(S35:U35)",
        "rowHammerTotal": ""
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 0
    },
    {
      "sourceRow": 36,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "32GB",
      "rank": "1Rx8",
      "boardCode": "BA5SRCA",
      "pcb": "欣强1Rx8 (贴8颗）BA5SRCA 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 9.8,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.5,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 36.43,
      "laserLogoRmb": 0.3,
      "customProcessRmb": 0.2,
      "customTotalRmb": 36.93,
      "rowHammerTestRmb": 6.0,
      "rowHammerTotalRmb": 37.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M36:R36)",
        "customTotal": "=SUM(S36:U36)",
        "rowHammerTotal": "=S36-P36+W36"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.43,
      "customAddOnRmb": 0.5,
      "rowHammerAddOnRmb": 1.5
    },
    {
      "sourceRow": 37,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "32GB",
      "rank": "2Rx8",
      "boardCode": "BA5SRCB",
      "pcb": "欣强2Rx8 (贴16颗）BA5SRCB 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.5,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 1.2,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 4.5,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 36.73,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 37.33,
      "rowHammerTestRmb": 6.0,
      "rowHammerTotalRmb": 38.23,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M37:R37)",
        "customTotal": "=SUM(S37:U37)",
        "rowHammerTotal": "=S37-P37+W37"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 8.73,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 1.5
    },
    {
      "sourceRow": 38,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "48GB",
      "rank": "2Rx8",
      "boardCode": "BA5SRCB",
      "pcb": "欣强2Rx8 (贴16颗）BA5SRCB 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.5,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 7.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 40.43,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 41.03,
      "rowHammerTestRmb": 9.0,
      "rowHammerTotalRmb": 42.43,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M38:R38)",
        "customTotal": "=SUM(S38:U38)",
        "rowHammerTotal": "=S38-P38+W38"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 12.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 2.0
    },
    {
      "sourceRow": 39,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "64GB",
      "rank": "2Rx8",
      "boardCode": "BA5S812",
      "pcb": "欣强2Rx8 (贴16颗）BA5S812",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 0,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 29.5,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 9.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 43.93,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 44.53,
      "rowHammerTestRmb": 11.0,
      "rowHammerTotalRmb": 45.93,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M39:R39)",
        "customTotal": "=SUM(S39:U39)",
        "rowHammerTotal": "=S39-P39+W39"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 14.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 2.0
    },
    {
      "sourceRow": 40,
      "factory": "晟中",
      "sourceFactory": "昇中",
      "moduleForm": "DDR5 SODIMM",
      "generation": "DDR5",
      "moduleType": "SODIMM",
      "capacity": "64GB",
      "rank": "2Rx8",
      "boardCode": "BA5SRCB",
      "pcb": "欣强2Rx8 (贴16颗）BA5SRCB 1.00",
      "spdHub": "辉芒微/亿存芯",
      "pmic": "立琪",
      "inductor": "新聿",
      "pcbCostRmb": 10.5,
      "pmicCostRmb": 6.4,
      "spdCostRmb": 4.5,
      "inductorCostRmb": 0.93,
      "rcCostRmb": 0,
      "pcbaBomRmb": 28.0,
      "coverCostRmb": 2.4,
      "smtCostRmb": 2.8,
      "testNoRowHammerRmb": 9.0,
      "freightRmb": 0.03,
      "packingRmb": 0.2,
      "standardTotalRmb": 42.43,
      "laserLogoRmb": 0.4,
      "customProcessRmb": 0.2,
      "customTotalRmb": 43.03,
      "rowHammerTestRmb": 11.0,
      "rowHammerTotalRmb": 44.43,
      "remark": "",
      "formulas": {
        "pcbaBom": "",
        "standardTotal": "=SUM(M40:R40)",
        "customTotal": "=SUM(S40:U40)",
        "rowHammerTotal": "=S40-P40+W40"
      },
      "matchedPartNumbers": [],
      "mappedPartNumber": "",
      "processingCostRmb": 14.43,
      "customAddOnRmb": 0.6,
      "rowHammerAddOnRmb": 2.0
    }
  ]
};
